---
#- name: tasks file for copy

#  tasks:

- name: copy container
  shell: |
    docker save petclinic:latest > /var/lib/jenkins/workspace/mpipe1_main/target/petclinicX.tar
    scp petclinicX.tar ubuntu@"{{ addr }}":/$HOME
